//
//	Instruction set for M68000 (definitions)
//	Link: http://info.sonicretro.org/SCHG:68000_Instruction_Set
//

#include "ins.hpp"

instruc_t Instructions[] = {
	{ "", 0 },
	{ "abcd", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "add", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "adda", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "addi", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "addq", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "addx", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "and", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "andi", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "asl", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "asr", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "b", CF_USE1 },
	{ "bchg", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "bclr", CF_CHG2 | CF_USE1 },
	{ "bra", CF_STOP | CF_USE1 },
	{ "bset", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "bsr", CF_CALL | CF_USE1 },
	{ "btst", CF_USE1 | CF_USE2 },
	{ "chk", CF_CALL | CF_USE1 | CF_USE2 },
	{ "clr", CF_CHG1 },
	{ "cmp", CF_USE1 | CF_USE2 },
	{ "cmpa", CF_USE1 | CF_USE2 },
	{ "cmpi", CF_USE1 | CF_USE2 },
	{ "cmpm", CF_USE1 | CF_USE2 },
	{ "db", CF_CHG1 | CF_USE1 | CF_USE2 },
	{ "divs", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "divu", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "eor", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "eori", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "exg", CF_CHG1 | CF_CHG2 | CF_USE2 },
	{ "ext", CF_CHG1 | CF_USE1 },
	{ "illegal", 0 },
	{ "jmp", CF_STOP | CF_USE1 | CF_JUMP },
	{ "jsr", CF_CALL | CF_USE1 },
	{ "lea", CF_CHG2 | CF_USE1 },
	{ "link", CF_CHG1 | CF_USE2 },
	{ "lsl", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "lsr", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "move", CF_CHG2 | CF_USE1 },
	{ "movea", CF_CHG2 | CF_USE1 },
	{ "movem", CF_CHG1 | CF_CHG2 },
	{ "movep", CF_CHG2 | CF_USE1 },
	{ "moveq", CF_CHG2 | CF_USE1 },
	{ "muls", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "mulu", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "nbcd", CF_CHG1 | CF_USE1 },
	{ "neg", CF_CHG1 | CF_USE1 },
	{ "negx", CF_CHG1 | CF_USE1 },
	{ "nop", 0 },
	{ "not", CF_CHG1 | CF_USE1 },
	{ "or", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "ori", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "pea", CF_USE1 },
	{ "reset", 0 },
	{ "rol", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "ror", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "roxl", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "roxr", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "rte", CF_STOP },
	{ "rtr", CF_STOP },
	{ "rts", CF_STOP },
	{ "sbcd", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "s", CF_CHG1 },
	{ "stop", CF_STOP },
	{ "sub", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "suba", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "subi", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "subq", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "subx", CF_CHG2 | CF_USE1 | CF_USE2 },
	{ "swap", CF_CHG1 | CF_USE1 },
	{ "tas", CF_CHG1 | CF_USE1 },
	{ "trap", CF_USE1 },
	{ "trapv", 0 },
	{ "tst", CF_USE1 },
	{ "unlk", CF_USE1 },
};
